# Assignment For Numpy
# Difficulty Level: Beginner

Q#1: Import the numpy package under the name np

In [1]:
import numpy as np

Q#2: Create a null vector of size 10

In [44]:
nullVector = np.empty_like(10)
nullVector

array([10])

Q#3: Create a vector with values ranging from 10 to 49

In [10]:
vector = np.arange(10, 50)

Q#4: Find the shape of previous array in question 3

In [13]:
vectorShape = np.shape(vector)

Q#5: Print the type of the previous array in question 3

In [16]:
vectorType = type(vector)

Q#6: Print the numpy version and the configuration

In [19]:
np.__version__, np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Khilji/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Khilji/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Khilji/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Khilji/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Khilji/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Khilji/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Khilji/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Khilji/anaconda3\\Library\\include']


('1.19.2', None)

Q#7: Print the dimension of the array in question 3

In [24]:
np.ndim(vector)

1

Q#8: Create a boolean array with all the True values

In [30]:
boolArray = np.full(10, True)
boolArray

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Q#9: Create a two dimensional array

In [31]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

Q#10: Create a three dimensional array

In [32]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Difficulty Level Easy

Q#11: Reverse a vector (first element becomes last)

In [38]:
vector = np.arange(10).reshape(5,2)
vector[::-1]

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

Q#12: Create a null vector of size 10 but the fifth value which is 1

In [57]:
nullVector = np.zeros(10)
nullVector[4] = 1
nullVector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Q#13: Create a 3x3 identity matrix

In [58]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Q#14: 
arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [62]:
arr = np.array([1, 2, 3, 4, 5])
np.array(arr, 'float32')

array([1., 2., 3., 4., 5.], dtype=float32)

Q#15: arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
           
Multiply arr1 with arr2

In [63]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
np.multiply(arr1, arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

Q#16: arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [73]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3 = arr1 == arr2
arr3

array([[False, False, False],
       [False, False, False]])

Q#17: Extract all odd numbers from arr with values(0-9)

In [74]:
arr = np.arange(0, 10)
oddNums = arr[arr%2 != 0]
oddNums

array([1, 3, 5, 7, 9])

Q#18: Replace all odd numbers to -1 from previous array

In [77]:
arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


Q#19: arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [81]:
arr = np.arange(10)
arr[[5, 6, 7, 8]]= 12 ### Or arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

Q#20: Create a 2d array with 1 on the border and 0 inside

In [82]:
arr2D = np.zeros(9).reshape(3,3)
arr2D[0:1,]=1
arr2D[:,0]=1
arr2D[:,-1]=1
arr2D[-1,]=1
arr2D

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Difficulty Level Medium

Q#21: arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [85]:
arr2d = np.array([[1, 2, 3],

        [4, 5, 6], 

        [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

Q#22: arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [87]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Q#23: Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [92]:
arr2D = np.arange(0, 10).reshape(5,2)
arr2D[0,]


array([0, 1])

Q#24: Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [95]:
arr3D = np.arange(0, 10).reshape(5,2)
arr3D[1,1]

3

Q#25: Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [99]:
arr2D = np.arange(0, 9).reshape(3,3)
arr2D[0:2, 2]

array([2, 5])

Q#26: Create a 10x10 array with random values and find the minimum and maximum values

In [105]:
arr = np.arange(0, 100).reshape(10, 10)
arr.max()
arr.min()

0

Q#27: a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [107]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= a[a == b]
c

array([2, 2, 4, 4])

Q#28: a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [110]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

Q#29: names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [118]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[np.where(names != 'Will')]

array([[ 0.41789805,  2.37651409, -1.05758942, -1.42877377],
       [-1.00330287, -0.51969069,  1.36468708, -0.427128  ],
       [ 1.46193979,  0.93968285,  1.25351038,  0.2578638 ],
       [ 1.27334983, -0.55773644, -0.59089823, -0.21695889],
       [-0.82392303,  0.36262715,  0.73654072, -0.8987408 ]])

Q#30: names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [122]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[np.where((names != 'Will') & (names != 'Joe'))]

array([[-0.31903219, -2.1645792 ,  0.87245404,  0.26670204],
       [-1.17879874, -1.47967156, -0.35639911, -0.09152688]])

# Difficulty Level Hard

Q#31: Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [127]:
arr2D = np.arange(1, 16).reshape(5,3)
arr2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Q#32: Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [129]:
arr = np.arange(1, 17).reshape(2, 2, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

Q#33: Swap axes of the array you created in Question 32

In [137]:
arr = np.arange(1, 17).reshape(2, 2, 4)
np.swapaxes(arr, 0, 2)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

Q#34: Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [144]:
arr10 = np.linspace(0, 10)
arr10[np.where(arr10 < 0.5)] = 0
arr10

array([ 0.        ,  0.        ,  0.        ,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Q#35: Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [153]:
arr1 = np.max(np.random.random(12))
arr2 = np.max(np.random.random(12))
arr3 = np.array([arr1, arr2])
arr3

array([0.69740213, 0.98205489])

Q#36: names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [154]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
set(names)

{'Bob', 'Joe', 'Will'}

Q#37: a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [156]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

Q#38: Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [159]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[0:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

Q#39: x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [161]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

Q#40: Generate a matrix of 20 random values and find its cumulative sum

In [171]:
mat = np.array(np.random.random(20)*10, "int32").reshape(5,4)
mat
np.cumsum(mat)

array([ 8, 17, 24, 24, 28, 28, 30, 37, 46, 52, 53, 57, 60, 65, 69, 75, 77,
       78, 78, 80], dtype=int32)