# NumPy Assignment#2:

In [2]:
import numpy as np

Q#1: Convert a 1D array to a 2D array with 2 rows?

In [3]:
np.arange(0, 10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q#2: How to stack two arrays vertically?

In [15]:
arr1 = np.arange(0, 10).reshape(2,5).astype("int32")
arr2 = np.ones(10).reshape(2,5).astype("int32")
np.vstack((arr1, arr2))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q#3: How to stack two arrays horizontally?

In [16]:
arr1 = np.arange(0, 10).reshape(2,5).astype("int32")
arr2 = np.ones(10).reshape(2,5).astype("int32")
np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q#4: How to convert an array of arrays into a flat 1d array?

In [20]:
arr1 = np.arange(0, 10).reshape(2,5)
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q#5: How to Convert higher dimension into one dimension?

In [25]:
arr1 = np.arange(0,20).reshape(4,5)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Q#6: Convert one dimension to higher dimension?

In [28]:
arr1 = np.arange(0, 20)
arr1.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Q#7: Create 5x5 an array and find the square of an array?

In [32]:
arr = np.arange(0, 25).reshape(5,5)
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

Q#8: Create 5x6 an array and find the mean?

In [33]:
arr = np.arange(0, 30).reshape(5,6)
arr.mean()

14.5

Q#9: Find the standard deviation of the previous array in Q8?

In [34]:
arr.std()

8.65544144839919

Q#10: Find the median of the previous array in Q8?

In [37]:
np.median(arr)

14.5

Q#11: Find the transpose of the previous array in Q8?

In [38]:
arr.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

Q#12: Create a 4x4 an array and find the sum of diagonal elements?

In [39]:
arr = np.arange(0, 16).reshape(4, 4)
np.trace(arr)

30

Q#13: Find the determinant of the previous array in Q12?

In [43]:
arr = np.arange(0, 16).reshape(4, 4)
np.linalg.det(arr)

0.0

Q#14: Find the 5th and 95th percentile of an array?

In [48]:
arr = np.arange(0, 16).reshape(4, 4)
print(np.percentile(arr, 5))
print(np.percentile(arr, 95))

0.75
14.25


Q#15: How to find if a given array has any null values?

In [53]:
arr = np.array(np.random.random(16), "int32").reshape(4, 4)
np.isnan(arr)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])